### ISSUE TITLE
missing code

### ISSUE THREAD

**Issue by bqey-xrsy** [yap231995/Diffusion-SCA#2]
I hope this message finds you well. I recently came across your project on GitHub, and I was impressed by the work you've done. As I delved deeper into the codebase, I noticed that there are two import statements missing:

from src.autoencoder import Autoencoder
from src.utils import aes_label_cpa_ascad

These imports seem crucial for the functionality of the project, particularly in relation to an autoencoder and AES label CPA ASCAD.

I would greatly appreciate it if you could provide me with the location of these missing code segments or any guidance on how to resolve this issue.

**Comment by trevor-yap** [comment]
Thank you for pointing this out! We have fixed this by importing the necessary stuff. If there is any more issue please let us know!
